/// <reference types="node" />

// SPDX-FileCopyrightText: 2026 Mario Gemoll
// SPDX-License-Identifier: 0BSD

/**
 * Cross-language fidelity test: verifies that the TypeScript Pong engine
 * produces the same outputs as the Python pong_env.py (the source of truth).
 *
 * Golden vectors are generated by:
 *   cd py && .venv/bin/python generate_pong_vectors.py
 *
 * Binary layout
 * ─────────────
 * environment.step-vectors.bin     N × 17 float32 (little-endian)
 *   input:   ball_row, ball_col, ball_vrow, ball_vcol, p1, p2, time  (7)
 *   actions: p1_action, p2_action                                    (2)
 *   output:  ball_row, ball_col, ball_vrow, ball_vcol, p1, p2, time  (7)
 *   done:    0.0 or 1.0                                              (1)
 *
 * environment.computer-vectors.bin M × 8 float32 (little-endian)
 *   input:   ball_row, ball_col, ball_vrow, ball_vcol, p1, p2, time  (7)
 *   action:  0.0, 1.0, or 2.0                                        (1)
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { computerPongPlayer, stepPongState } from './environment';
import type { PongAction, PongState } from './types';

const __dirname = dirname(fileURLToPath(import.meta.url));

function readF32(name: string): Float32Array {
  const buf = readFileSync(join(__dirname, name));
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
}

function rowToState(d: Float32Array, offset: number): PongState {
  return {
    ballRow:  d[offset],
    ballCol:  d[offset + 1],
    ballVRow: d[offset + 2],
    ballVCol: d[offset + 3],
    p1Center: d[offset + 4],
    p2Center: d[offset + 5],
    time:     d[offset + 6]
  };
}

// ── Step vectors ──────────────────────────────────────────────────────────────

const STEP_STRIDE = 17;
const stepData = readF32('environment.step-vectors.bin');
const nStep = stepData.length / STEP_STRIDE;

describe('stepPongState matches Python pong_env', () => {
  for (let i = 0; i < nStep; i++) {
    it(`vector ${String(i)}`, () => {
      const base = i * STEP_STRIDE;
      const input     = rowToState(stepData, base);
      const p1Action  = stepData[base + 7] as PongAction;
      const p2Action  = stepData[base + 8] as PongAction;
      const expected  = rowToState(stepData, base + 9);
      const expDone = stepData[base + 16] === 1;

      const { state: out, done } = stepPongState(input, p1Action, p2Action);

      // Python uses float32, TS uses float64 — allow for float32/float64 rounding
      expect(out.ballRow,  'ballRow').toBeCloseTo(expected.ballRow,  5);
      expect(out.ballCol,  'ballCol').toBeCloseTo(expected.ballCol,  5);
      expect(out.ballVRow, 'ballVRow').toBeCloseTo(expected.ballVRow, 5);
      expect(out.ballVCol, 'ballVCol').toBeCloseTo(expected.ballVCol, 5);
      expect(out.p1Center, 'p1Center').toBeCloseTo(expected.p1Center, 5);
      expect(out.p2Center, 'p2Center').toBeCloseTo(expected.p2Center, 5);
      expect(out.time,     'time').toBe(expected.time);
      expect(done,         'done').toBe(expDone);
    });
  }
});

// ── Computer-player vectors ───────────────────────────────────────────────────

const COMPUTER_STRIDE = 8;
const computerData = readF32('environment.computer-vectors.bin');
const nComputer = computerData.length / COMPUTER_STRIDE;

describe('computerPongPlayer matches Python pong_env', () => {
  for (let i = 0; i < nComputer; i++) {
    it(`vector ${String(i)}`, () => {
      const base   = i * COMPUTER_STRIDE;
      const input  = rowToState(computerData, base);
      const action = computerData[base + 7] as PongAction;
      expect(computerPongPlayer(input)).toBe(action);
    });
  }
});
