/// <reference types="node" />

// SPDX-FileCopyrightText: 2026 Mario Gemoll
// SPDX-License-Identifier: 0BSD

/**
 * Cross-language fidelity test: verifies TypeScript pendulum dynamics match
 * Python Gymnax Pendulum-v1 for one-step transitions.
 *
 * Golden vectors are generated by:
 *   cd py && .venv/bin/python generate_pendulum_vectors.py
 *
 * Binary layout
 * ─────────────
 * environment.step-vectors.bin     N x 11 float32 (little-endian)
 *   input:   theta, theta_dot, elapsed_steps, torque                   (4)
 *   output:  theta, theta_dot, cos(theta), sin(theta), theta_dot       (5)
 *   reward:  reward                                                     (1)
 *   trunc:   0.0 or 1.0                                                (1)
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { stepPendulumState } from './environment';

const __dirname = dirname(fileURLToPath(import.meta.url));

function readF32(name: string): Float32Array {
  const buf = readFileSync(join(__dirname, name));
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
}

const STEP_STRIDE = 11;
const stepData = readF32('environment.step-vectors.bin');
const nStep = stepData.length / STEP_STRIDE;

describe('stepPendulumState matches Python gymnax Pendulum-v1', () => {
  for (let i = 0; i < nStep; i++) {
    it(`vector ${String(i)}`, () => {
      const base = i * STEP_STRIDE;
      const theta = stepData[base];
      const thetaDot = stepData[base + 1];
      const elapsedSteps = Math.trunc(stepData[base + 2]);
      const torque = stepData[base + 3];

      const expectedTheta = stepData[base + 4];
      const expectedThetaDot = stepData[base + 5];
      const expectedObs0 = stepData[base + 6];
      const expectedObs1 = stepData[base + 7];
      const expectedObs2 = stepData[base + 8];
      const expectedReward = stepData[base + 9];
      const expectedTruncated = stepData[base + 10] === 1;

      const out = stepPendulumState({ theta, thetaDot }, elapsedSteps, torque);

      // Python vectors are float32, TS math is float64.
      expect(out.state.theta, 'theta').toBeCloseTo(expectedTheta, 5);
      expect(out.state.thetaDot, 'thetaDot').toBeCloseTo(expectedThetaDot, 5);
      expect(out.obs[0], 'obs[0]').toBeCloseTo(expectedObs0, 5);
      expect(out.obs[1], 'obs[1]').toBeCloseTo(expectedObs1, 5);
      expect(out.obs[2], 'obs[2]').toBeCloseTo(expectedObs2, 5);
      expect(out.reward, 'reward').toBeCloseTo(expectedReward, 5);
      expect(out.truncated, 'truncated').toBe(expectedTruncated);
      expect(out.steps, 'steps').toBe(elapsedSteps + 1);
    });
  }
});
